%% Demo: Hf_true -> Hobs -> Hf_hat, then compare

clear; clc;

%% 1) Generate full-band frequency-domain CSI
Ns = 1;
SCS = 15;                      % kHz
Nsub = 624;                    % = 52 RB * 12
TxArraySize = [2 2 2 1 1];     % [M N P Mg Ng]
RxArraySize = [1 1 2 1 1];
delaySpread = 300e-9;          % seconds
cdlProfile = "CDL-A";
seed = 20260226;

Hf_true = generate_cdl_freq_csi( ...
    Ns, SCS, Nsub, ...
    TxArraySize, RxArraySize, ...
    delaySpread, cdlProfile, seed);

%% 2) Carrier / CSI-RS configuration
carrier = nrCarrierConfig;
carrier.NSizeGrid = Nsub / 12;
carrier.SubcarrierSpacing = SCS;

ofdmInfo = nrOFDMInfo(carrier);
Nfft = ofdmInfo.Nfft;

csirs = nrCSIRSConfig;
csirs.RowNumber = 1;
csirs.Density = 'three';
csirs.SymbolLocations = {6};
csirs.SubcarrierLocations = {0};

%% 3) Extract sparse CSI-RS observations
[Hobs, scIdx, maskInfo] = extract_csirs_observations(Hf_true, carrier, csirs);

disp(['Number of observed subcarriers = ' num2str(numel(scIdx))]);

%% 4) Reconstruct full-band Hf_hat from Hobs
% Try one of: "zerofill", "linear", "pchip", "spline"
method = "pchip";

Hf_hat = reconstruct_Hf_from_Hobs(Hobs, scIdx, Nsub, method);

%% 5) Compare visually
plot_Hf_sample({Hf_true, Hf_hat}, 1, 1, 1, ...
    'Labels', {'Hf true', ['Hf hat (' char(method) ')']}, ...
    'Scale', 'db', ...
    'ScIdx', scIdx, ...
    'Hobs', Hobs, ...
    'ObsLabel', 'CSI-RS observations', ...
    'TitleText', ['H_f true vs reconstructed (' char(method) ')']);

%% 6) Compute simple relative error
hTrue = squeeze(Hf_true(1,1,1,:));
hHat  = squeeze(Hf_hat(1,1,1,:));

nmse = norm(hTrue - hHat)^2 / max(norm(hTrue)^2, eps);
fprintf('NMSE (sample=1, tx=1, rx=1): %.6e (%.2f dB)\n', nmse, 10*log10(nmse + eps));

%% 7) Optional: compare multiple reconstruction methods at once
% Hf_hat_zero  = reconstruct_Hf_from_Hobs(Hobs, scIdx, Nsub, "zerofill");
Hf_hat_lin   = reconstruct_Hf_from_Hobs(Hobs, scIdx, Nsub, "linear");
Hf_hat_pchip = reconstruct_Hf_from_Hobs(Hobs, scIdx, Nsub, "pchip");

% plot_Hf_sample({Hf_true, Hf_hat_zero, Hf_hat_lin, Hf_hat_pchip}, 1, 1, 1, ...
%     'Labels', {'True', 'Zero-fill', 'Linear', 'PCHIP'}, ...
%     'Scale', 'db', ...
%     'ScIdx', scIdx, ...
%     'Hobs', Hobs, ...
%     'ObsLabel', 'CSI-RS observations', ...
%     'TitleText', 'H_f reconstruction comparison');
plot_Hf_sample({Hf_true, Hf_hat_lin, Hf_hat_pchip}, 1, 1, 1, ...
    'Labels', {'True', 'Linear', 'PCHIP'}, ...
    'Scale', 'db', ...
    'ScIdx', scIdx, ...
    'Hobs', Hobs, ...
    'ObsLabel', 'CSI-RS observations', ...
    'TitleText', 'H_f reconstruction comparison');

%% 8) Convert Hf_true / Hf_hat to delay-domain CSI and compare
Ntap = 32;

% Ht_true = freq_to_delay_csi(Hf_true, Ntap);
% Ht_hat  = freq_to_delay_csi(Hf_hat,  Ntap);

Ht_true = freq_to_delay_csi_twosided_fullgrid(Hf_true, Nfft, Ntap);
Ht_hat  = freq_to_delay_csi_twosided_fullgrid(Hf_hat,  Nfft, Ntap);

plot_Ht_sample({Ht_true, Ht_hat}, 1, 1, 1, ...
    'Labels', {'Ht true', ['Ht hat (' char(method) ')']}, ...
    'Mode', 'db', ...
    'PlotType', 'stem', ...
    'TitleText', ['H_t true vs reconstructed (' char(method) ')']);

%% 9) Delay-domain NMSE
htTrue = squeeze(Ht_true(1,1,1,:));
htHat  = squeeze(Ht_hat(1,1,1,:));

nmse_t = norm(htTrue - htHat)^2 / max(norm(htTrue)^2, eps);
fprintf('Delay-domain NMSE (sample=1, tx=1, rx=1): %.6e (%.2f dB)\n', ...
    nmse_t, 10*log10(nmse_t + eps));

%% 10) Optional: compare multiple reconstruction methods in delay domain
% Ht_hat_zero  = freq_to_delay_csi(Hf_hat_zero,  Ntap);
Ht_hat_lin   = freq_to_delay_csi(Hf_hat_lin,   Ntap);
Ht_hat_pchip = freq_to_delay_csi(Hf_hat_pchip, Ntap);

% plot_Ht_sample({Ht_true, Ht_hat_zero, Ht_hat_lin, Ht_hat_pchip}, 1, 1, 1, ...
%     'Labels', {'True', 'Zero-fill', 'Linear', 'PCHIP'}, ...
%     'Mode', 'db', ...
%     'PlotType', 'line', ...
%     'TitleText', 'H_t reconstruction comparison');
plot_Ht_sample({Ht_true, Ht_hat_lin, Ht_hat_pchip}, 1, 1, 1, ...
    'Labels', {'True', 'Linear', 'PCHIP'}, ...
    'Mode', 'db', ...
    'PlotType', 'line', ...
    'TitleText', 'H_t reconstruction comparison');

%% 11) Reconstruct frequency-domain from Ht_hat

Hf_t2f_hat = delay_to_freq_csi_twosided_fullgrid(Ht_hat, Nfft, Nsub);

plot_Hf_sample({Hf_true, Hf_t2f_hat}, 1, 1, 1, ...
    'Labels', {'True', 'Linear'}, ...
    'Scale', 'db', ...
    'ScIdx', scIdx, ...
    'Hobs', Hobs, ...
    'ObsLabel', 'CSI-RS observations', ...
    'TitleText', 'H_f reconstruction comparison');